version: "3.9"

services:
  api:
    build: ./api
    volumes:
      - image_data:/image_data:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.earth-wallpaper.rule=Host(`earth.${DOMAINNAME}`)

  daemon:
    build: ./daemon
    env_file:
      - ./daemon/.env
    volumes:
      - image_data:/image_data

volumes:
  image_data: {}
